export const metadata = {
  title: 'ChatEcho | Chatting Platform ',
  description: 'Generated by Next.js',
}
import '../styles/global.css'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
