export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '../styles/global.css'
import Header from "@/app/components/header";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header/>
      {children}
      </body>
    </html>
  )
}
